/**
 * Seed a test customer account + API token.
 * Run once: npx tsx scripts/seed-test-account.ts
 *
 * Outputs a .env.test file with the token ready for the agent simulator.
 */

import { createClient } from "@supabase/supabase-js";
import { createHash, randomBytes } from "crypto";
import { writeFileSync } from "fs";

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error(
    "Add SUPABASE_SERVICE_ROLE_KEY to .env.local — get it from:\n" +
    "https://supabase.com/dashboard/project/gcvoqlahswwhckwxdesu/settings/api\n"
  );
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

function sha256(text: string) {
  return createHash("sha256").update(text).digest("hex");
}

async function main() {
  console.log("Setting up test account...\n");

  // 1. Create auth user
  const TEST_EMAIL = "test-customer@adskills-test.dev";
  const TEST_PASSWORD = "TestCustomer123!";

  const { data: existingUser } = await supabase.auth.admin.listUsers();
  const existing = existingUser?.users.find((u) => u.email === TEST_EMAIL);

  let userId: string;

  if (existing) {
    console.log(`✓ Auth user already exists: ${TEST_EMAIL}`);
    userId = existing.id;
  } else {
    const { data: newUser, error } = await supabase.auth.admin.createUser({
      email: TEST_EMAIL,
      password: TEST_PASSWORD,
      email_confirm: true,
      user_metadata: { role: "org" },
    });
    if (error) throw new Error(`Failed to create user: ${error.message}`);
    userId = newUser.user.id;
    console.log(`✓ Created auth user: ${TEST_EMAIL} (${userId})`);
  }

  // 2. Create or find org
  const ORG_NAME = "AdSkills Test Agency";
  let orgId: string;

  const { data: existingOrg } = await supabase
    .from("orgs")
    .select("id")
    .eq("name", ORG_NAME)
    .maybeSingle();

  if (existingOrg) {
    orgId = existingOrg.id;
    console.log(`✓ Org already exists: ${ORG_NAME} (${orgId})`);
  } else {
    const { data: org, error } = await supabase
      .from("orgs")
      .insert({ name: ORG_NAME })
      .select()
      .single();
    if (error) throw new Error(`Failed to create org: ${error.message}`);
    orgId = org.id;
    console.log(`✓ Created org: ${ORG_NAME} (${orgId})`);
  }

  // 3. Link user to org
  const { error: linkError } = await supabase
    .from("org_users")
    .upsert({ user_id: userId, org_id: orgId }, { onConflict: "user_id" });
  if (linkError) throw new Error(`Failed to link user to org: ${linkError.message}`);
  console.log(`✓ Linked user to org`);

  // 4. Create API token
  const plainToken = `ask_test_${randomBytes(24).toString("hex")}`;
  const tokenHash = sha256(plainToken);

  const { error: tokenError } = await supabase.from("api_tokens").insert({
    org_id: orgId,
    token_hash: tokenHash,
    label: "Test Agent Token",
  });

  if (tokenError) {
    if (tokenError.message.includes("unique")) {
      console.log(`✓ Token already exists for this org`);
    } else {
      throw new Error(`Failed to create token: ${tokenError.message}`);
    }
  } else {
    console.log(`✓ Created API token`);
  }

  // 5. Create a welcome announcement for the test account
  const { data: announcement } = await supabase
    .from("announcements")
    .select("id")
    .eq("title", "Welcome to AdSkills Dashboard")
    .maybeSingle();

  if (!announcement) {
    await supabase.from("announcements").insert({
      title: "Welcome to AdSkills Dashboard",
      message:
        "Track your skill usage, detect advertising platforms, and get AI-powered improvement suggestions.",
      announcement_type: "new_feature",
      severity: "info",
      featured: true,
      action_url: "/dashboard/analytics",
      action_label: "Explore Analytics",
    });
    console.log(`✓ Created welcome announcement`);
  }

  // 6. Write env file for agent simulator
  const envContent = [
    `# Generated by seed-test-account.ts`,
    `ADSKILLS_API_URL=${SUPABASE_URL}/functions/v1`,
    `ADSKILLS_API_TOKEN=${plainToken}`,
    `TEST_ORG_ID=${orgId}`,
    `TEST_USER_ID=${userId}`,
    `TEST_EMAIL=${TEST_EMAIL}`,
    `TEST_PASSWORD=${TEST_PASSWORD}`,
  ].join("\n");

  writeFileSync(".env.test", envContent);

  console.log(`\n✓ Wrote credentials to .env.test`);
  console.log(`\nTest account ready:`);
  console.log(`  Email:    ${TEST_EMAIL}`);
  console.log(`  Password: ${TEST_PASSWORD}`);
  console.log(`  Org:      ${ORG_NAME} (${orgId})`);
  console.log(`  Token:    ${plainToken}`);
  console.log(`\nRun the agent: npx tsx scripts/agent-simulator.ts`);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
